language: node_js
node_js:
  - "7"
cache:
  directories:
    - node_modules
before_script:
  - npm prune
script:
  - npm test
notifications:
    slack: blathome:rUL5aNk7S6jBDrYguVMqIWy4
    email: false
# deploy:
#   provider: pages
#   skip_cleanup: true
#   github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
#   on:
#     branch: master
# how to deploy to github pages by travis: https://stackoverflow.com/questions/23277391/how-to-publish-to-github-pages-from-travis-ci
after_success:
  if [ -n "$GITHUB_TOKEN" ]; then
    git config --global user.name "Travis-CI";
    git config --global user.email "travis@example.com";
    npm run deploy;
  fi
